#index:
#    path: /
#    controller: App\Controller\DefaultController::index

root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /app
        permanent: true