resources:
  App\Entity\exercices\RefPrenoms:
    collectionOperations:
      create_user:
        method: get
        path: '/api/ref-prenoms'
        openapi_context:
          summary: Random rabbit picture
          description: >
            # Pop a great rabbit picture by color!

            ![A great rabbit](https://rabbit.org/graphics/fun/netbunnies/jellybean1-brennan1.jpg)